# Generated by Django 5.1.3 on 2024-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("menu", models.URLField()),
                ("logo", models.URLField()),
                ("free_shipping_price", models.IntegerField()),
                ("categories", models.ManyToManyField(related_name="restaurants", to="restaurants.category")),
            ],
        ),
    ]
