# Generated by Django 5.1.3 on 2024-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_menu_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
