# Generated by Django 5.1.3 on 2024-12-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_product_weight_unit_alter_product_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"),
        ),
    ]
