# Generated by Django 5.1.3 on 2024-12-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0006_alter_product_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "restaurant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="restaurants.menucategory"
            ),
            preserve_default=False,
        ),
    ]
