# Generated by Django 5.1.3 on 2024-12-20 18:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_menucategory_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="menucategory",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
