# Generated by Django 5.1.3 on 2024-12-20 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0008_alter_menucategory_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="menucategory",
            managers=[],
        ),
    ]
