# Generated by Django 5.1.3 on 2024-12-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_alter_menucategory_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menucategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("name", "restaurant")},
        ),
    ]
