# Generated by Django 5.1.3 on 2024-12-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_alter_menucategory_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="RestaurantCategory",
        ),
    ]
