# Generated by Django 5.1.3 on 2024-12-22 02:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0011_rename_category_restaurantcategory"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="name_product_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="name_restaurant_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
