# Generated by Django 5.1.3 on 2024-12-22 02:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0012_product_name_product_gin_index_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="menucategory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="name_menu_category_gin_index", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
