# Generated by Django 5.1.3 on 2024-12-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracked_carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedcart",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Matched"), (False, "Close")], default=True, verbose_name="Статус"
            ),
        ),
    ]
